package com.example.greenmarket.db

import com.example.greenmarket.db.model.ProdottiInRicette
import com.example.greenmarket.db.model.Prodotto
import com.example.greenmarket.db.model.Ricetta

class CreazioneOggetti {

    fun getProdotti(): List<Prodotto> {
        val prodotti = listOf(
            Prodotto(nome = "Mele", descrizione = "Alta qualità e freschezza garantita.", prezzo = 1.99f, foto = "", "kg"),
            Prodotto(nome = "Pere", descrizione = "Gustose e nutrienti.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Noci", descrizione = "Frutta secca, fonte di grassi gustosa e adatta anche nelle insalate.", prezzo = 5.49f, foto = "",   "kg"),
            Prodotto(nome = "Banane", descrizione = "Ideali per uno spuntino veloce.", prezzo = 1.79f, foto = "",   "kg"),
            Prodotto(nome = "Melanzane", descrizione = "Perfette per grigliate.", prezzo = 2.99f, foto = "",   "kg"),
            Prodotto(nome = "Pomodori", descrizione = "Succosi e freschi.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Carote", descrizione = "Croccanti e dolci.", prezzo = 1.29f, foto = "",   "kg"),
            Prodotto(nome = "Patate", descrizione = "Versatili e nutrienti.", prezzo = 0.99f, foto = "",   "kg"),
            Prodotto(nome = "Spinaci", descrizione = "Ricchi di ferro.", prezzo = 2.19f, foto = "",   "kg"),
            Prodotto(nome = "Arance", descrizione = "Dolci e succose.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Limoni", descrizione = "Ideali per bevande e condimenti.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Ananas", descrizione = "Dolce e tropicale.", prezzo = 2.99f, foto = "", "kg"),
            Prodotto(nome = "Fragole", descrizione = "Dolci e succose, perfette per dessert.", prezzo = 3.49f, foto = "", "kg"),
            Prodotto(nome = "Zucchine", descrizione = "Ideali per zuppe e insalate.", prezzo = 1.79f, foto = "", "kg"),
            Prodotto(nome = "Cetrioli", descrizione = "Freschi e croccanti, perfetti per insalate.", prezzo = 1.49f, foto = "", "kg"),
            Prodotto(nome = "Peperoni", descrizione = "Dolci e colorati, ideali per grigliate.", prezzo = 2.99f, foto = "", "kg"),
            Prodotto(nome = "Uva", descrizione = "Dolce e succosa, perfetta per spuntini.", prezzo = 2.49f, foto = "", "kg"),
            Prodotto(nome = "Mirtilli", descrizione = "Ricchi di antiossidanti, perfetti per snack.", prezzo = 3.99f, foto = "", "kg"),
            Prodotto(nome = "Kiwi", descrizione = "Dolci e acidi, ricchi di vitamina C.", prezzo = 1.99f, foto = "", "kg"),
            Prodotto(nome = "Mango", descrizione = "Dolce e tropicale, perfetto per smoothie.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Ciliegie", descrizione = "Dolci e succose, perfette per dessert.", prezzo = 3.99f, foto = "",   "kg"),
            Prodotto(nome = "Lamponi", descrizione = "Dolci e leggermente acidi, perfetti per dolci.", prezzo = 3.49f, foto = "",   "kg"),
            Prodotto(nome = "Avocado", descrizione = "Cremoso e nutriente, ideale per toast.", prezzo = 2.99f, foto = "",   "kg"),
            Prodotto(nome = "Cavolfiore", descrizione = "Versatile e nutriente, perfetto per zuppe.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Broccoli", descrizione = "Ricchi di vitamine, ideali per contorni.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Fagiolini", descrizione = "Croccanti e freschi, perfetti per contorni.", prezzo = 2.99f, foto = "",   "kg"),
            Prodotto(nome = "Piselli", descrizione = "Dolci e teneri, ideali per contorni.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Zucca", descrizione = "Dolce e cremosa, perfetta per zuppe.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Cipolle", descrizione = "Versatili e aromatiche, ideali per cucinare.", prezzo = 1.29f, foto = "",   "kg"),
            Prodotto(nome = "Aglio", descrizione = "Aromatico e saporito, ideale per condimenti.", prezzo = 0.99f, foto = "",   "kg"),
            Prodotto(nome = "Ravanelli", descrizione = "Croccanti e leggermente piccanti, perfetti per insalate.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Asparagi", descrizione = "Delicati e nutrienti, ideali per contorni.", prezzo = 3.49f, foto = "",   "kg"),
            Prodotto(nome = "Finocchi", descrizione = "Freschi e aromatici, perfetti per insalate.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Sedano", descrizione = "Croccante e fresco, ideale per zuppe.", prezzo = 1.29f, foto = "",   "kg"),
            Prodotto(nome = "Prezzemolo", descrizione = "Aromatico e fresco, ideale per condimenti.", prezzo = 0.99f, foto = "",   "kg"),
            Prodotto(nome = "Basilico", descrizione = "Aromatico e fresco, perfetto per insalate.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Rosmarino", descrizione = "Aromatico e intenso, ideale per arrosti.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Salvia", descrizione = "Aromatica e intensa, ideale per condimenti.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Timo", descrizione = "Aromatico e fresco, perfetto per insalate.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Origano", descrizione = "Aromatico e intenso, ideale per pizze.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Lattuga", descrizione = "Fresca e croccante, perfetta per insalate.", prezzo = 1.29f, foto = "",   "kg"),
            Prodotto(nome = "Radicchio", descrizione = "Fresco e leggermente amaro, ideale per insalate.", prezzo = 1.99f, foto = "",   "kg"),
            Prodotto(nome = "Cavolo", descrizione = "Nutriente e croccante, ideale per zuppe.", prezzo = 1.49f, foto = "",   "kg"),
            Prodotto(nome = "Porro", descrizione = "Delicati e aromatici, perfetti per zuppe.", prezzo = 2.49f, foto = "",   "kg"),
            Prodotto(nome = "Melone", descrizione = "Dolce e succoso, perfetto per spuntini estivi.", prezzo = 2.99f, foto = "",   "kg"),
            Prodotto(nome = "Anguria", descrizione = "Dolce e rinfrescante, ideale per l'estate.", prezzo = 3.49f, foto = "",   "kg"),
            Prodotto("Pane", "Da GreenMarket trovi l'originale pane pugliese, morbido e saporito al punto giusto", 5.99f, "", "kg"),
            Prodotto("Cicorie", "Deliziose verdure perfette per zuppe, ma anche per essere gustate fredde con un po' d'olio.", 3.49f, "", "kg"),
            Prodotto("Mozzarella", "Uno dei latticini più buoni che esista, direttamente dal nostro caseificio.", 4.99f, "", "kg"),
            Prodotto("Riso", "Valida alternativa alla pasta, buona sia per i risotti, ma anche per fresche insalate estive.", 1.49f, "", "kg"),
            Prodotto("Cioccolato", "Buono per i dolci, ma perfetto anche insieme alla frutta.", 5.99f, "", "kg"),
            Prodotto("Menta", "Dal gusto rinfrescante, trova applicazione in primi piatti freddi, ma anche in cocktail e insieme alla frutta.", 3.49f, "", "kg"),
            Prodotto("Feta", "Formaggio di origine ellenica, è l'ingrediente che caratterizza la famosa insalata greca", 5.99f, "", "kg"),
        )
        return prodotti
    }

    fun getRicette(): List<Ricetta> {
        val ricette = listOf(
            Ricetta(nome = "Torta di Mele", descrizione = "Mescola farina, zucchero, uova e mele. Cuoci in forno a 180°C per 40 minuti.", foto = ""),
            Ricetta(nome = "Insalata di Pere e Noci", descrizione = "Mescola pere affettate con noci, lattuga e un condimento a base di olio e aceto.", foto = ""),
            Ricetta(nome = "Frullato di Banane", descrizione = "Frulla banane con latte e un po' di miele per una bevanda dolce e sana.", foto = ""),
            Ricetta(nome = "Parmigiana di Melanzane", descrizione = "Stratifica melanzane fritte con salsa di pomodoro e formaggio. Cuoci in forno.", foto = ""),
            Ricetta(nome = "Pomodori Ripieni", descrizione = "Riempi pomodori con un mix di riso, verdure e spezie. Cuoci in forno.", foto = ""),
            Ricetta(nome = "Carote Glaciate", descrizione = "Cuoci carote con burro e zucchero fino a renderle tenere e caramellate.", foto = ""),
            Ricetta(nome = "Patate Arrosto", descrizione = "Cuoci patate con olio d'oliva, rosmarino e sale fino a renderle croccanti.", foto = ""),
            Ricetta(nome = "Zuppa di Spinaci", descrizione = "Cuoci spinaci con brodo di pollo e crema. Frulla fino a ottenere una zuppa liscia.", foto = ""),
            Ricetta(nome = "Spremuta d'Arancia", descrizione = "Spremi arance fresche per una bevanda rinfrescante e ricca di vitamine.", foto = ""),
            Ricetta(nome = "Tè al Limone", descrizione = "Prepara un tè nero e aggiungi succo di limone per un gusto fresco e agrumato.", foto = ""),
            Ricetta(nome = "Ananas Caramellato", descrizione = "Cuoci fette di ananas con zucchero e burro fino a renderle caramellate.", foto = ""),
            Ricetta(nome = "Cheesecake alle Fragole", descrizione = "Prepara una base di biscotti e coprila con una crema di formaggio e fragole.", foto = ""),
            Ricetta(nome = "Zucchine Ripiene", descrizione = "Riempi zucchine con carne macinata, formaggio e spezie. Cuoci in forno.", foto = ""),
            Ricetta(nome = "Insalata di Cetrioli", descrizione = "Affetta i cetrioli e condiscili con aceto, sale e pepe.", foto = ""),
            Ricetta(nome = "Peperoni Grigliati", descrizione = "Griglia peperoni con olio d'oliva, sale e pepe fino a renderli teneri.", foto = ""),
            Ricetta(nome = "Uva al Formaggio", descrizione = "Servi chicchi d'uva con formaggio cremoso per un antipasto raffinato.", foto = ""),
            Ricetta(nome = "Muffin ai Mirtilli", descrizione = "Prepara una pastella per muffin e aggiungi mirtilli freschi prima di cuocere.", foto = ""),
            Ricetta(nome = "Insalata di Kiwi e Avocado", descrizione = "Mescola kiwi e avocado a cubetti con un condimento di olio e limone.", foto = ""),
            Ricetta(nome = "Ciliegie al Cioccolato", descrizione = "Immergi ciliegie nel cioccolato fuso e lascia raffreddare.", foto = ""),
            Ricetta(nome = "Lamponi con Yogurt", descrizione = "Servi lamponi freschi con yogurt greco e miele.", foto = ""),
            Ricetta(nome = "Toast all'Avocado", descrizione = "Spalma avocado schiacciato su pane tostato e aggiungi sale e pepe.", foto = ""),
            Ricetta(nome = "Cavolfiore al Forno", descrizione = "Cuoci cavolfiore con olio d'oliva, sale e pepe fino a renderlo dorato.", foto = ""),
            Ricetta(nome = "Broccoli al Vapore", descrizione = "Cuoci broccoli al vapore e condisci con olio d'oliva e limone.", foto = ""),
            Ricetta(nome = "Fagiolini in Padella", descrizione = "Salta fagiolini con aglio e olio d'oliva fino a renderli teneri.", foto = ""),
            Ricetta(nome = "Piselli con Pancetta", descrizione = "Cuoci piselli con pancetta e cipolla per un contorno saporito.", foto = ""),
            Ricetta(nome = "Vellutata di Zucca", descrizione = "Cuoci zucca con brodo e crema. Frulla fino a ottenere una vellutata liscia.", foto = ""),
            Ricetta(nome = "Cipolle Caramellate", descrizione = "Cuoci cipolle con burro e zucchero fino a renderle caramellate.", foto = ""),
            Ricetta(nome = "Aglio Arrostito", descrizione = "Cuoci teste d'aglio intere con olio d'oliva fino a renderle morbide.", foto = ""),
            Ricetta(nome = "Insalata di Ravanelli", descrizione = "Affetta ravanelli e condiscili con olio, aceto e sale.", foto = ""),
            Ricetta(nome = "Asparagi alla Griglia", descrizione = "Griglia asparagi con olio d'oliva, sale e pepe fino a renderli teneri.", foto = ""),
            Ricetta(nome = "Insalata di Finocchi", descrizione = "Affetta finocchi e condiscili con olio, limone e sale.", foto = ""),
            Ricetta(nome = "Zuppa di Sedano", descrizione = "Cuoci sedano con brodo e patate. Frulla fino a ottenere una zuppa liscia.", foto = ""),
            Ricetta(nome = "Pesto di Prezzemolo", descrizione = "Frulla prezzemolo con olio, aglio e pinoli per un pesto fresco.", foto = ""),
            Ricetta(nome = "Insalata Caprese", descrizione = "Alterna fette di pomodoro e mozzarella. Aggiungi basilico fresco e olio d'oliva.", foto = ""),
            Ricetta(nome = "Patate al Rosmarino", descrizione = "Cuoci patate con rosmarino e olio d'oliva fino a renderle croccanti.", foto = ""),
            Ricetta(nome = "Burro alla Salvia", descrizione = "Sciogli burro con foglie di salvia e servi su pasta o carne.", foto = ""),
            Ricetta(nome = "Timo su Pollo Arrosto", descrizione = "Condisci pollo con timo fresco, sale e pepe prima di arrostire.", foto = ""),
            Ricetta(nome = "Pizza all'Origano", descrizione = "Condisci la pizza con origano fresco prima di infornare.", foto = ""),
            Ricetta(nome = "Insalata di Lattuga", descrizione = "Mescola lattuga con cetrioli, pomodori e un condimento a base di olio e aceto.", foto = ""),
            Ricetta(nome = "Radicchio alla Griglia", descrizione = "Griglia radicchio con olio d'oliva, sale e pepe fino a renderlo tenero.", foto = ""),
            Ricetta(nome = "Zuppa di Cavolo", descrizione = "Cuoci cavolo con brodo e patate. Frulla fino a ottenere una zuppa liscia.", foto = ""),
            Ricetta(nome = "Porri e Patate", descrizione = "Cuoci porri con patate e brodo fino a renderli teneri.", foto = ""),
            Ricetta(nome = "Insalata di Melone", descrizione = "Mescola melone a cubetti con prosciutto e rucola.", foto = ""),
            Ricetta(nome = "Anguria alla Menta", descrizione = "Servi fette di anguria con foglie di menta fresca.", foto = ""),
            Ricetta("Carote al Forno", "Taglia le carote a bastoncini. Condiscile con olio, sale e rosmarino. Cuoci in forno a 200°C per 20 minuti.", ""),
            Ricetta("Insalata di Carote e Arance", "Grattugia le carote e mescolale con fette di arancia e un pizzico di sale.", ""),
            Ricetta("Ratatouille", "Soffriggi melanzane, zucchine, peperoni e pomodori a cubetti. Cuoci a fuoco lento per 30 minuti.", ""),
            Ricetta("Gazpacho", "Frulla pomodori, cetrioli, peperoni, cipolle, aceto e olio d'oliva. Servi freddo.", ""),
            Ricetta("Torta di Carote", "Mescola farina, zucchero, carote grattugiate, uova e olio. Cuoci in forno a 180°C per 40 minuti.", ""),
            Ricetta("Crostata di Fragole", "Prepara una base di pasta frolla. Farcisci con fragole e cuoci in forno a 180°C per 30 minuti.", ""),
            Ricetta("Frittata di Spinaci", "Sbatti le uova e mescolale con spinaci saltati in padella. Cuoci fino a quando la frittata è dorata.", ""),
            Ricetta("Tzatziki", "Mescola cetrioli grattugiati, yogurt greco, aglio tritato e aneto. Servi freddo.", ""),
            Ricetta("Insalata di Cavolo e Mela", "Taglia il cavolo a julienne e mescolalo con fettine di mela e una vinaigrette leggera.", ""),
            Ricetta("Spaghetti al Pesto di Zucchine", "Frulla zucchine, olio, aglio, pinoli e basilico. Mescola con gli spaghetti cotti.", ""),
            Ricetta("Smoothie di Fragole e Banane", "Frulla fragole, banane e succo d'arancia fino a ottenere una consistenza liscia.", ""),
            Ricetta("Pane al Rosmarino", "Mescola farina, lievito, acqua e rosmarino tritato. Lascia lievitare e cuoci in forno a 200°C per 25 minuti.", ""),
            Ricetta("Insalata di Pollo e Avocado", "Griglia il pollo e taglialo a strisce. Mescola con avocado, insalata mista e un condimento leggero.", ""),
            Ricetta("Patate e Fagiolini al Vapore", "Cuoci a vapore patate e fagiolini fino a quando sono teneri. Condisci con olio d'oliva e sale.", ""),
            Ricetta("Muffin ai Lamponi", "Mescola farina, zucchero, uova e lamponi. Versa il composto negli stampini e cuoci in forno a 180°C per 20 minuti.", ""),
            Ricetta("Insalata di Cavolo e Carote", "Taglia cavolo e carote a julienne. Mescola con una vinaigrette leggera.", ""),
            Ricetta("Pizza Margherita", "Prepara la base per la pizza. Aggiungi salsa di pomodoro, mozzarella e basilico. Cuoci in forno a 220°C per 15 minuti.", ""),
            Ricetta("Smoothie di Kiwi e Menta", "Frulla kiwi, menta fresca e succo di mela fino a ottenere una consistenza liscia.", ""),
            Ricetta("Tiramisù alle Fragole", "Alterna strati di savoiardi inzuppati nel succo di fragole e crema al mascarpone. Guarnisci con fragole fresche.", ""),
            Ricetta("Sformato di Patate e Cipolle", "Affetta patate e cipolle. Alterna strati in una teglia, aggiungi formaggio e cuoci in forno a 180°C per 40 minuti.", ""),
            Ricetta("Risotto agli Asparagi", "Soffriggi cipolla e riso. Aggiungi brodo e asparagi tagliati a pezzi. Cuoci fino a quando il riso è cremoso.", ""),
            Ricetta("Insalata di Finocchi e Arance", "Taglia finocchi e arance a fettine sottili. Condisci con olio d'oliva e sale.", ""),
            Ricetta("Zuppa di Lenticchie", "Cuoci lenticchie con cipolle, carote, sedano e brodo vegetale. Frulla una parte per una consistenza cremosa.", ""),
            Ricetta("Frittata di Cipolle", "Soffriggi cipolle affettate. Sbatti le uova e versale sulle cipolle. Cuoci fino a quando la frittata è dorata.", ""),
            Ricetta("Insalata di Cetrioli e Yogurt", "Mescola cetrioli a fettine con yogurt, aglio e aneto. Servi freddo.", ""),
            Ricetta("Risotto al Limone", "Soffriggi cipolla e riso. Aggiungi brodo e succo di limone. Cuoci fino a quando il riso è cremoso.", ""),
            Ricetta("Bruschette al Pomodoro", "Tosta fette di pane. Aggiungi pomodori a dadini, aglio, olio d'oliva e basilico.", ""),
            Ricetta("Insalata di Anguria e Feta", "Mescola cubetti di anguria con feta sbriciolata e menta fresca.", ""),
            Ricetta("Polpette di Melanzane", "Griglia le melanzane e frullale. Mescola con pangrattato e formaggio. Forma delle polpette e cuoci in forno.", ""),
            Ricetta("Minestrone di Verdure", "Cuoci una varietà di verdure con brodo vegetale fino a quando sono tenere.", ""),
            Ricetta("Pasta e Piselli", "Cuoci la pasta. Aggiungi piselli cotti e una salsa leggera di burro e parmigiano.", ""),
            Ricetta("Insalata di Pomodori e Cetrioli", "Mescola pomodori a dadini e cetrioli a fettine con olio d'oliva e aceto.", ""),
            Ricetta("Torta Salata di Zucchine", "Mescola zucchine grattugiate con uova, farina e formaggio. Versa in una teglia e cuoci in forno a 180°C per 30 minuti.", ""),
            Ricetta("Pan Cott", "Metti in una pentola acqua, alloro, aglio e olio; quando bolle butta le patate; quasi a fine cottura butta le cicorie; a fine cottura butta il pane raffermo. Scola tutto e aggiungi olive, olio e cipolle rosse a crudo.", ""),
            Ricetta("Insalata Greca", "Metti insieme feta, pomodori, cetrioli, cipolla, peperoni, origano e olive nere. Condisci con sale e olio e lascia insaporire prima di gustarlo.", "")
        )
        return ricette
    }

    fun getProdInRicette() : List<ProdottiInRicette> {
        val prodInRicette = listOf(
            ProdottiInRicette("Torta di Mele", "Mele"),
            ProdottiInRicette("Insalata di Pere e Noci", "Pere"),
            ProdottiInRicette("Insalata di Pere e Noci", "Noci"),
            ProdottiInRicette("Frullato di Banane", "Banane"),
            ProdottiInRicette("Parmigiana di Melanzane", "Melanzane"),
            ProdottiInRicette("Parmigiana di Melanzane", "Mozzarella"),
            ProdottiInRicette("Pomodori Ripieni", "Pomodori"),
            ProdottiInRicette("Pomodori Ripieni", "Riso"),
            ProdottiInRicette("Carote Glaciate", "Carote"),
            ProdottiInRicette("Patate Arrosto", "Patate"),
            ProdottiInRicette("Zuppa di Spinaci", "Spinaci"),
            ProdottiInRicette("Spremuta d'Arancia", "Arance"),
            ProdottiInRicette("Tè al Limone", "Limoni"),
            ProdottiInRicette("Ananas Caramellato", "Ananas"),
            ProdottiInRicette("Cheesecake alle Fragole", "Fragole"),
            ProdottiInRicette("Zucchine Ripiene", "Zucchine"),
            ProdottiInRicette("Insalata di Cetrioli", "Cetrioli"),
            ProdottiInRicette("Peperoni Grigliati", "Peperoni"),
            ProdottiInRicette("Uva al Formaggio", "Uva"),
            ProdottiInRicette("Muffin ai Mirtilli", "Mirtilli"),
            ProdottiInRicette("Insalata di Kiwi e Avocado", "Kiwi"),
            ProdottiInRicette("Insalata di Kiwi e Avocado", "Avocado"),
            ProdottiInRicette("Ciliegie al Cioccolato", "Ciliegie"),
            ProdottiInRicette("Ciliegie al Cioccolato", "Cioccolato"),
            ProdottiInRicette("Lamponi con Yogurt", "Lamponi"),
            ProdottiInRicette("Toast all'Avocado", "Avocado"),
            ProdottiInRicette("Cavolfiore al Forno", "Cavolfiore"),
            ProdottiInRicette("Broccoli al Vapore", "Broccoli"),
            ProdottiInRicette("Fagiolini in Padella", "Fagiolini"),
            ProdottiInRicette("Piselli con Pancetta", "Piselli"),
            ProdottiInRicette("Vellutata di Zucca", "Zucca"),
            ProdottiInRicette("Cipolle Caramellate", "Cipolle"),
            ProdottiInRicette("Aglio Arrostito", "Aglio"),
            ProdottiInRicette("Insalata di Ravanelli", "Ravanelli"),
            ProdottiInRicette("Asparagi alla Griglia", "Asparagi"),
            ProdottiInRicette("Insalata di Finocchi", "Finocchi"),
            ProdottiInRicette("Zuppa di Sedano", "Sedano"),
            ProdottiInRicette("Pesto di Prezzemolo", "Prezzemolo"),
            ProdottiInRicette("Insalata Caprese", "Pomodori"),
            ProdottiInRicette("Insalata Caprese", "Mozzarella"),
            ProdottiInRicette("Insalata Caprese", "Basilico"),
            ProdottiInRicette("Patate al Rosmarino", "Patate"),
            ProdottiInRicette("Burro alla Salvia", "Salvia"),
            ProdottiInRicette("Timo su Pollo Arrosto", "Timo"),
            ProdottiInRicette("Pizza all'Origano", "Origano"),
            ProdottiInRicette("Insalata di Lattuga", "Lattuga"),
            ProdottiInRicette("Radicchio alla Griglia", "Radicchio"),
            ProdottiInRicette("Zuppa di Cavolo", "Cavolo"),
            ProdottiInRicette("Porri e Patate", "Porro"),
            ProdottiInRicette("Porri e Patate", "Patate"),
            ProdottiInRicette("Insalata di Melone", "Melone"),
            ProdottiInRicette("Anguria alla Menta", "Anguria"),
            ProdottiInRicette("Anguria alla Menta", "Menta"),
            ProdottiInRicette("Carote al Forno", "Carote"),
            ProdottiInRicette("Insalata di Carote e Arance", "Carote"),
            ProdottiInRicette("Insalata di Carote e Arance", "Arance"),
            ProdottiInRicette("Ratatouille", "Melanzane"),
            ProdottiInRicette("Ratatouille", "Zucchine"),
            ProdottiInRicette("Ratatouille", "Peperoni"),
            ProdottiInRicette("Ratatouille", "Pomodori"),
            ProdottiInRicette("Gazpacho", "Pomodori"),
            ProdottiInRicette("Gazpacho", "Cetrioli"),
            ProdottiInRicette("Gazpacho", "Peperoni"),
            ProdottiInRicette("Gazpacho", "Cipolle"),
            ProdottiInRicette("Torta di Carote", "Carote"),
            ProdottiInRicette("Crostata di Fragole", "Fragole"),
            ProdottiInRicette("Frittata di Spinaci", "Spinaci"),
            ProdottiInRicette("Tzatziki", "Cetrioli"),
            ProdottiInRicette("Insalata di Cavolo e Mela", "Cavolo"),
            ProdottiInRicette("Insalata di Cavolo e Mela", "Mele"),
            ProdottiInRicette("Spaghetti al Pesto di Zucchine", "Zucchine"),
            ProdottiInRicette("Smoothie di Fragole e Banane", "Fragole"),
            ProdottiInRicette("Smoothie di Fragole e Banane", "Banane"),
            ProdottiInRicette("Pane al Rosmarino", "Rosmarino"),
            ProdottiInRicette("Insalata di Pollo e Avocado", "Avocado"),
            ProdottiInRicette("Patate e Fagiolini al Vapore", "Patate"),
            ProdottiInRicette("Patate e Fagiolini al Vapore", "Fagiolini"),
            ProdottiInRicette("Muffin ai Lamponi", "Lamponi"),
            ProdottiInRicette("Insalata di Cavolo e Carote", "Cavolo"),
            ProdottiInRicette("Insalata di Cavolo e Carote", "Carote"),
            ProdottiInRicette("Pizza Margherita", "Pomodori"),
            ProdottiInRicette("Pizza Margherita", "Mozzarella"),
            ProdottiInRicette("Smoothie di Kiwi e Menta", "Kiwi"),
            ProdottiInRicette("Smoothie di Kiwi e Menta", "Menta"),
            ProdottiInRicette("Tiramisù alle Fragole", "Fragole"),
            ProdottiInRicette("Sformato di Patate e Cipolle", "Patate"),
            ProdottiInRicette("Sformato di Patate e Cipolle", "Cipolle"),
            ProdottiInRicette("Risotto agli Asparagi", "Asparagi"),
            ProdottiInRicette("Insalata di Finocchi e Arance", "Finocchi"),
            ProdottiInRicette("Insalata di Finocchi e Arance", "Arance"),
            ProdottiInRicette("Zuppa di Lenticchie", "Cipolle"),
            ProdottiInRicette("Zuppa di Lenticchie", "Carote"),
            ProdottiInRicette("Frittata di Cipolle", "Cipolle"),
            ProdottiInRicette("Insalata di Cetrioli e Yogurt", "Cetrioli"),
            ProdottiInRicette("Risotto al Limone", "Limoni"),
            ProdottiInRicette("Bruschette al Pomodoro", "Pomodori"),
            ProdottiInRicette("Insalata di Anguria e Feta", "Anguria"),
            ProdottiInRicette("Insalata di Anguria e Feta", "Feta"),
            ProdottiInRicette("Polpette di Melanzane", "Melanzane"),
            ProdottiInRicette("Minestrone di Verdure", "Zucchine"),
            ProdottiInRicette("Minestrone di Verdure", "Carote"),
            ProdottiInRicette("Minestrone di Verdure", "Fagiolini"),
            ProdottiInRicette("Pasta e Piselli", "Piselli"),
            ProdottiInRicette("Insalata di Pomodori e Cetrioli", "Pomodori"),
            ProdottiInRicette("Insalata di Pomodori e Cetrioli", "Cetrioli"),
            ProdottiInRicette("Torta Salata di Zucchine", "Zucchine"),
            ProdottiInRicette("Pan Cott", "Pane"),
            ProdottiInRicette("Pan Cott", "Cicorie"),
            ProdottiInRicette("Insalata Greca", "Feta")
        )
        return prodInRicette
    }

}